export interface EmojiEntry {
  emoji: string;
  keywords: string[];
}

export interface EmojiCategory {
  id: string;
  label: string;
  icon: string;
  emojis: EmojiEntry[];
}

export const EMOJI_CATEGORIES: EmojiCategory[] = [
  {
    id: 'frequent',
    label: 'Frequentes',
    icon: '🕐',
    emojis: [
      { emoji: '📋', keywords: ['clipboard','lista','notas'] },
      { emoji: '📝', keywords: ['memo','nota','escrever'] },
      { emoji: '🎯', keywords: ['alvo','meta','objetivo'] },
      { emoji: '💡', keywords: ['lampada','ideia','luz'] },
      { emoji: '🚀', keywords: ['foguete','lancamento','rapido'] },
      { emoji: '⭐', keywords: ['estrela','favorito'] },
      { emoji: '✅', keywords: ['check','feito','pronto'] },
      { emoji: '📌', keywords: ['pin','fixar','importante'] },
      { emoji: '🔥', keywords: ['fogo','quente','popular'] },
      { emoji: '💼', keywords: ['maleta','trabalho','negocios'] },
      { emoji: '📚', keywords: ['livros','estudo','leitura'] },
      { emoji: '🏠', keywords: ['casa','lar','home'] },
    ],
  },
  {
    id: 'smileys',
    label: 'Rostos e Emoções',
    icon: '😀',
    emojis: [
      { emoji: '😀', keywords: ['sorriso','feliz','alegre'] },
      { emoji: '😃', keywords: ['sorriso','feliz','olhos'] },
      { emoji: '😄', keywords: ['sorriso','feliz','contente'] },
      { emoji: '😁', keywords: ['sorriso','dentes','feliz'] },
      { emoji: '😆', keywords: ['rindo','feliz'] },
      { emoji: '😅', keywords: ['suor','nervoso','alivio'] },
      { emoji: '🤣', keywords: ['rindo','rolando','muito'] },
      { emoji: '😂', keywords: ['rindo','chorando','alegria'] },
      { emoji: '🙂', keywords: ['sorriso','leve'] },
      { emoji: '🙃', keywords: ['invertido','ironico'] },
      { emoji: '😉', keywords: ['piscada','piscar'] },
      { emoji: '😊', keywords: ['sorriso','corado','feliz'] },
      { emoji: '😇', keywords: ['anjo','aureola','inocente'] },
      { emoji: '🥰', keywords: ['amor','coracoes','apaixonado'] },
      { emoji: '😍', keywords: ['amor','olhos','coracoes'] },
      { emoji: '🤩', keywords: ['estrelas','incrivel','uau'] },
      { emoji: '😘', keywords: ['beijo','amor'] },
      { emoji: '😗', keywords: ['beijo','assobio'] },
      { emoji: '😚', keywords: ['beijo','corado'] },
      { emoji: '😙', keywords: ['beijo','sorriso'] },
      { emoji: '🥲', keywords: ['sorriso','lagrima','triste'] },
      { emoji: '😋', keywords: ['delicioso','gostoso','lingua'] },
      { emoji: '😛', keywords: ['lingua','brincadeira'] },
      { emoji: '😜', keywords: ['lingua','piscada','louco'] },
      { emoji: '🤪', keywords: ['louco','maluco','doido'] },
      { emoji: '😝', keywords: ['lingua','apertado'] },
      { emoji: '🤑', keywords: ['dinheiro','rico','ganancia'] },
      { emoji: '🤗', keywords: ['abraco','caloroso'] },
      { emoji: '🤭', keywords: ['ops','mao','boca'] },
      { emoji: '🤫', keywords: ['silencio','segredo','shh'] },
      { emoji: '🤔', keywords: ['pensando','duvida','hmm'] },
      { emoji: '🫡', keywords: ['saudacao','respeito'] },
      { emoji: '🤐', keywords: ['ziper','boca','calado'] },
      { emoji: '🤨', keywords: ['sobrancelha','desconfiado'] },
      { emoji: '😐', keywords: ['neutro','serio','inexpressivo'] },
      { emoji: '😑', keywords: ['serio','inexpressivo'] },
      { emoji: '😶', keywords: ['sem','boca','mudo'] },
      { emoji: '🫥', keywords: ['pontilhado','invisivel'] },
      { emoji: '😏', keywords: ['malicioso','convencido'] },
      { emoji: '😒', keywords: ['chateado','entediado'] },
      { emoji: '🙄', keywords: ['olhos','revirando','tedioso'] },
      { emoji: '😬', keywords: ['tenso','desconfortavel'] },
      { emoji: '🤥', keywords: ['mentira','nariz'] },
      { emoji: '😌', keywords: ['aliviado','calmo','paz'] },
      { emoji: '😔', keywords: ['triste','pensativo','chateado'] },
      { emoji: '😪', keywords: ['sonolento','cansado'] },
      { emoji: '🤤', keywords: ['babando','fome'] },
      { emoji: '😴', keywords: ['dormindo','sono','zzz'] },
      { emoji: '😷', keywords: ['mascara','doente','gripe'] },
      { emoji: '🤒', keywords: ['termometro','febre','doente'] },
      { emoji: '🤕', keywords: ['bandagem','ferido','dor'] },
      { emoji: '🤢', keywords: ['enjoado','verde','nausea'] },
      { emoji: '🤮', keywords: ['vomitando','passando','mal'] },
      { emoji: '🥵', keywords: ['quente','calor','suando'] },
      { emoji: '🥶', keywords: ['frio','congelando','gelo'] },
      { emoji: '🥴', keywords: ['tonto','bebado','zonzo'] },
      { emoji: '😵', keywords: ['tonto','espiral','confuso'] },
      { emoji: '🤯', keywords: ['mente','explodindo','chocado'] },
      { emoji: '🤠', keywords: ['cowboy','chapeu'] },
      { emoji: '🥳', keywords: ['festa','celebracao','comemoracao'] },
      { emoji: '🥸', keywords: ['disfarce','oculos','bigode'] },
      { emoji: '😎', keywords: ['oculos','sol','legal','cool'] },
      { emoji: '🤓', keywords: ['nerd','estudioso','oculos'] },
      { emoji: '🧐', keywords: ['monoculo','investigando'] },
      { emoji: '😭', keywords: ['chorando','muito','triste'] },
      { emoji: '😱', keywords: ['gritando','medo','horror'] },
      { emoji: '😈', keywords: ['diabo','mal','travesso'] },
      { emoji: '👿', keywords: ['diabo','bravo','irritado'] },
      { emoji: '💀', keywords: ['caveira','morte','perigo'] },
      { emoji: '☠️', keywords: ['caveira','ossos','pirata'] },
      { emoji: '👻', keywords: ['fantasma','boo','halloween'] },
      { emoji: '👽', keywords: ['alienigena','et','espacial'] },
      { emoji: '🤖', keywords: ['robo','maquina','tecnologia'] },
      { emoji: '🎃', keywords: ['abobora','halloween'] },
      { emoji: '😺', keywords: ['gato','sorriso','feliz'] },
      { emoji: '😸', keywords: ['gato','sorriso','olhos'] },
      { emoji: '😹', keywords: ['gato','rindo','alegria'] },
      { emoji: '😻', keywords: ['gato','amor','coracoes'] },
      { emoji: '🙈', keywords: ['macaco','nao','ver'] },
      { emoji: '🙉', keywords: ['macaco','nao','ouvir'] },
      { emoji: '🙊', keywords: ['macaco','nao','falar'] },
    ],
  },
  {
    id: 'people',
    label: 'Pessoas e Gestos',
    icon: '👋',
    emojis: [
      { emoji: '👋', keywords: ['aceno','oi','tchau'] },
      { emoji: '🤚', keywords: ['mao','levantada','pare'] },
      { emoji: '🖐️', keywords: ['mao','aberta','cinco'] },
      { emoji: '✋', keywords: ['mao','pare','oi'] },
      { emoji: '🖖', keywords: ['vulcano','spock'] },
      { emoji: '👌', keywords: ['ok','perfeito','otimo'] },
      { emoji: '🤌', keywords: ['dedos','italiano'] },
      { emoji: '🤏', keywords: ['pitada','pouco','pequeno'] },
      { emoji: '✌️', keywords: ['paz','vitoria','dois'] },
      { emoji: '🤞', keywords: ['dedos','cruzados','sorte'] },
      { emoji: '🫰', keywords: ['coracao','mao'] },
      { emoji: '🤟', keywords: ['amor','rock','mao'] },
      { emoji: '🤘', keywords: ['rock','metal','chifres'] },
      { emoji: '🤙', keywords: ['telefone','liga','hang'] },
      { emoji: '👈', keywords: ['apontando','esquerda'] },
      { emoji: '👉', keywords: ['apontando','direita'] },
      { emoji: '👆', keywords: ['apontando','cima'] },
      { emoji: '👇', keywords: ['apontando','baixo'] },
      { emoji: '☝️', keywords: ['dedo','cima','atencao'] },
      { emoji: '🫵', keywords: ['apontando','voce'] },
      { emoji: '👍', keywords: ['joinha','legal','bom','positivo'] },
      { emoji: '👎', keywords: ['negativo','ruim','nao'] },
      { emoji: '✊', keywords: ['punho','forca','luta'] },
      { emoji: '👊', keywords: ['soco','punho','forca'] },
      { emoji: '🤛', keywords: ['punho','esquerda'] },
      { emoji: '🤜', keywords: ['punho','direita'] },
      { emoji: '👏', keywords: ['palmas','aplausos','parabens'] },
      { emoji: '🙌', keywords: ['maos','celebracao','viva'] },
      { emoji: '🫶', keywords: ['coracao','maos','amor'] },
      { emoji: '🤝', keywords: ['aperto','maos','acordo'] },
      { emoji: '🙏', keywords: ['orar','por favor','obrigado'] },
      { emoji: '💪', keywords: ['musculo','forte','forca'] },
      { emoji: '🦾', keywords: ['braco','mecanico','robo'] },
      { emoji: '👶', keywords: ['bebe','crianca','nenem'] },
      { emoji: '👦', keywords: ['menino','garoto'] },
      { emoji: '👧', keywords: ['menina','garota'] },
      { emoji: '👨', keywords: ['homem','adulto'] },
      { emoji: '👩', keywords: ['mulher','adulta'] },
      { emoji: '🧑', keywords: ['pessoa','adulto'] },
      { emoji: '👴', keywords: ['idoso','avo','velho'] },
      { emoji: '👵', keywords: ['idosa','avo','velha'] },
      { emoji: '🧑‍💻', keywords: ['programador','computador','dev'] },
      { emoji: '🧑‍🎓', keywords: ['estudante','formatura','escola'] },
      { emoji: '🧑‍🏫', keywords: ['professor','escola','ensino'] },
      { emoji: '🧑‍🔬', keywords: ['cientista','laboratorio','ciencia'] },
      { emoji: '🧑‍🎨', keywords: ['artista','arte','pintura'] },
      { emoji: '🧑‍🍳', keywords: ['cozinheiro','chef','culinaria'] },
      { emoji: '🧑‍🚀', keywords: ['astronauta','espaco'] },
      { emoji: '🧑‍⚕️', keywords: ['medico','saude','hospital'] },
      { emoji: '🏃', keywords: ['correndo','exercicio','rapido'] },
      { emoji: '🚶', keywords: ['andando','caminhando'] },
      { emoji: '💃', keywords: ['dancando','mulher','danca'] },
      { emoji: '🕺', keywords: ['dancando','homem','danca'] },
    ],
  },
  {
    id: 'hearts',
    label: 'Corações e Símbolos',
    icon: '❤️',
    emojis: [
      { emoji: '❤️', keywords: ['coracao','vermelho','amor'] },
      { emoji: '🧡', keywords: ['coracao','laranja'] },
      { emoji: '💛', keywords: ['coracao','amarelo'] },
      { emoji: '💚', keywords: ['coracao','verde'] },
      { emoji: '💙', keywords: ['coracao','azul'] },
      { emoji: '💜', keywords: ['coracao','roxo'] },
      { emoji: '🖤', keywords: ['coracao','preto'] },
      { emoji: '🤍', keywords: ['coracao','branco'] },
      { emoji: '🤎', keywords: ['coracao','marrom'] },
      { emoji: '💔', keywords: ['coracao','partido','triste'] },
      { emoji: '❤️‍🔥', keywords: ['coracao','fogo','paixao'] },
      { emoji: '💕', keywords: ['coracoes','dois','amor'] },
      { emoji: '💞', keywords: ['coracoes','girando'] },
      { emoji: '💓', keywords: ['coracao','batendo'] },
      { emoji: '💗', keywords: ['coracao','crescendo'] },
      { emoji: '💖', keywords: ['coracao','brilhando'] },
      { emoji: '💘', keywords: ['coracao','flecha','cupido'] },
      { emoji: '💝', keywords: ['coracao','presente','laco'] },
      { emoji: '💟', keywords: ['coracao','decoracao'] },
      { emoji: '♥️', keywords: ['coracao','carta','naipe'] },
      { emoji: '💯', keywords: ['cem','perfeito','nota'] },
      { emoji: '💢', keywords: ['raiva','irritado'] },
      { emoji: '💥', keywords: ['explosao','impacto','boom'] },
      { emoji: '💫', keywords: ['tonto','estrela','brilho'] },
      { emoji: '💦', keywords: ['gotas','suor','agua'] },
      { emoji: '💨', keywords: ['vento','rapido','correndo'] },
      { emoji: '🕊️', keywords: ['pomba','paz'] },
      { emoji: '💬', keywords: ['balao','fala','mensagem'] },
      { emoji: '💭', keywords: ['balao','pensamento'] },
      { emoji: '🗯️', keywords: ['balao','raiva','grito'] },
    ],
  },
  {
    id: 'nature',
    label: 'Natureza e Animais',
    icon: '🌿',
    emojis: [
      { emoji: '🐶', keywords: ['cachorro','cao','dog'] },
      { emoji: '🐱', keywords: ['gato','cat','felino'] },
      { emoji: '🐭', keywords: ['rato','ratinho','mouse'] },
      { emoji: '🐹', keywords: ['hamster','roedor'] },
      { emoji: '🐰', keywords: ['coelho','bunny'] },
      { emoji: '🦊', keywords: ['raposa','fox'] },
      { emoji: '🐻', keywords: ['urso','bear'] },
      { emoji: '🐼', keywords: ['panda','urso'] },
      { emoji: '🐨', keywords: ['coala','australia'] },
      { emoji: '🐯', keywords: ['tigre','selvagem'] },
      { emoji: '🦁', keywords: ['leao','rei','selvagem'] },
      { emoji: '🐮', keywords: ['vaca','boi','fazenda'] },
      { emoji: '🐷', keywords: ['porco','fazenda'] },
      { emoji: '🐸', keywords: ['sapo','verde'] },
      { emoji: '🐵', keywords: ['macaco','monkey'] },
      { emoji: '🐔', keywords: ['galinha','frango'] },
      { emoji: '🐧', keywords: ['pinguim','gelo'] },
      { emoji: '🐦', keywords: ['passaro','ave'] },
      { emoji: '🦅', keywords: ['aguia','eagle'] },
      { emoji: '🦋', keywords: ['borboleta','butterfly'] },
      { emoji: '🐛', keywords: ['inseto','bug','bicho'] },
      { emoji: '🐝', keywords: ['abelha','mel'] },
      { emoji: '🐞', keywords: ['joaninha','sorte'] },
      { emoji: '🐢', keywords: ['tartaruga','lento'] },
      { emoji: '🐍', keywords: ['cobra','serpente'] },
      { emoji: '🦎', keywords: ['lagarto','reptil'] },
      { emoji: '🐙', keywords: ['polvo','mar'] },
      { emoji: '🦈', keywords: ['tubarao','mar'] },
      { emoji: '🐬', keywords: ['golfinho','mar'] },
      { emoji: '🐳', keywords: ['baleia','mar','oceano'] },
      { emoji: '🌸', keywords: ['flor','cerejeira','rosa'] },
      { emoji: '🌺', keywords: ['flor','hibisco'] },
      { emoji: '🌻', keywords: ['girassol','flor','amarelo'] },
      { emoji: '🌹', keywords: ['rosa','flor','amor'] },
      { emoji: '🌷', keywords: ['tulipa','flor'] },
      { emoji: '🌼', keywords: ['flor','margarida'] },
      { emoji: '🌿', keywords: ['folha','verde','planta'] },
      { emoji: '🍀', keywords: ['trevo','sorte','quatro'] },
      { emoji: '🍃', keywords: ['folha','vento'] },
      { emoji: '🌱', keywords: ['broto','crescendo','planta'] },
      { emoji: '🌲', keywords: ['arvore','pinheiro','verde'] },
      { emoji: '🌳', keywords: ['arvore','frondosa'] },
      { emoji: '🍁', keywords: ['folha','outono','maple'] },
      { emoji: '🍂', keywords: ['folhas','outono','caidas'] },
      { emoji: '🌾', keywords: ['trigo','arroz','colheita'] },
      { emoji: '🌵', keywords: ['cacto','deserto'] },
      { emoji: '🌴', keywords: ['palmeira','praia','tropical'] },
      { emoji: '🌊', keywords: ['onda','mar','oceano'] },
      { emoji: '🌈', keywords: ['arcoiris','cores'] },
      { emoji: '☀️', keywords: ['sol','dia','quente'] },
      { emoji: '🌤️', keywords: ['sol','nuvem','parcial'] },
      { emoji: '⛅', keywords: ['nublado','sol','nuvem'] },
      { emoji: '🌙', keywords: ['lua','noite','crescente'] },
      { emoji: '🌍', keywords: ['terra','mundo','globo'] },
      { emoji: '❄️', keywords: ['neve','floco','frio','inverno'] },
      { emoji: '⛄', keywords: ['boneco','neve','inverno'] },
      { emoji: '🌪️', keywords: ['tornado','tempestade'] },
      { emoji: '🌋', keywords: ['vulcao','erupcao'] },
      { emoji: '🏔️', keywords: ['montanha','neve'] },
      { emoji: '⛰️', keywords: ['montanha'] },
    ],
  },
  {
    id: 'food',
    label: 'Comida e Bebida',
    icon: '🍕',
    emojis: [
      { emoji: '🍎', keywords: ['maca','fruta','vermelha'] },
      { emoji: '🍊', keywords: ['laranja','fruta','tangerina'] },
      { emoji: '🍋', keywords: ['limao','fruta','amarelo'] },
      { emoji: '🍌', keywords: ['banana','fruta'] },
      { emoji: '🍉', keywords: ['melancia','fruta','vermelha'] },
      { emoji: '🍇', keywords: ['uva','fruta','roxa'] },
      { emoji: '🍓', keywords: ['morango','fruta'] },
      { emoji: '🫐', keywords: ['mirtilo','blueberry'] },
      { emoji: '🍒', keywords: ['cereja','fruta'] },
      { emoji: '🍑', keywords: ['pessego','fruta'] },
      { emoji: '🥝', keywords: ['kiwi','fruta'] },
      { emoji: '🍍', keywords: ['abacaxi','fruta','tropical'] },
      { emoji: '🥭', keywords: ['manga','fruta'] },
      { emoji: '🥑', keywords: ['abacate','guacamole'] },
      { emoji: '🥦', keywords: ['brocolis','vegetal','verde'] },
      { emoji: '🥕', keywords: ['cenoura','vegetal'] },
      { emoji: '🌽', keywords: ['milho','espiga'] },
      { emoji: '🍕', keywords: ['pizza','comida','italiano'] },
      { emoji: '🍔', keywords: ['hamburguer','lanche','fast'] },
      { emoji: '🍟', keywords: ['batata','frita','fast'] },
      { emoji: '🌮', keywords: ['taco','mexicano'] },
      { emoji: '🌯', keywords: ['burrito','mexicano','wrap'] },
      { emoji: '🍜', keywords: ['ramen','macarrao','sopa'] },
      { emoji: '🍝', keywords: ['espaguete','macarrao','pasta'] },
      { emoji: '🍣', keywords: ['sushi','japones','peixe'] },
      { emoji: '🍱', keywords: ['bento','japones','marmita'] },
      { emoji: '🥗', keywords: ['salada','saudavel','verde'] },
      { emoji: '🍰', keywords: ['bolo','fatia','doce'] },
      { emoji: '🎂', keywords: ['bolo','aniversario','vela'] },
      { emoji: '🧁', keywords: ['cupcake','doce','bolinho'] },
      { emoji: '🍩', keywords: ['donut','rosquinha','doce'] },
      { emoji: '🍪', keywords: ['cookie','biscoito','doce'] },
      { emoji: '🍫', keywords: ['chocolate','doce','barra'] },
      { emoji: '🍬', keywords: ['bala','doce','candy'] },
      { emoji: '🍭', keywords: ['pirulito','doce'] },
      { emoji: '☕', keywords: ['cafe','xicara','quente'] },
      { emoji: '🍵', keywords: ['cha','xicara','quente'] },
      { emoji: '🧃', keywords: ['suco','caixinha','bebida'] },
      { emoji: '🥤', keywords: ['copo','canudo','refrigerante'] },
      { emoji: '🍺', keywords: ['cerveja','caneca','bebida'] },
      { emoji: '🍷', keywords: ['vinho','taca','bebida'] },
      { emoji: '🥂', keywords: ['brinde','champagne','celebracao'] },
      { emoji: '🧊', keywords: ['gelo','cubo','gelado'] },
    ],
  },
  {
    id: 'objects',
    label: 'Objetos e Ferramentas',
    icon: '💡',
    emojis: [
      { emoji: '📄', keywords: ['pagina','documento','papel'] },
      { emoji: '📝', keywords: ['memo','nota','escrever'] },
      { emoji: '📋', keywords: ['clipboard','prancheta','lista'] },
      { emoji: '📌', keywords: ['pin','alfinete','fixar'] },
      { emoji: '📎', keywords: ['clip','anexo','prender'] },
      { emoji: '💡', keywords: ['lampada','ideia','luz'] },
      { emoji: '🎯', keywords: ['alvo','meta','objetivo','dardo'] },
      { emoji: '🚀', keywords: ['foguete','lancamento','rapido'] },
      { emoji: '💰', keywords: ['dinheiro','saco','moeda'] },
      { emoji: '💵', keywords: ['dolar','nota','dinheiro'] },
      { emoji: '💳', keywords: ['cartao','credito','pagamento'] },
      { emoji: '📊', keywords: ['grafico','barras','dados'] },
      { emoji: '📈', keywords: ['grafico','subindo','crescimento'] },
      { emoji: '📉', keywords: ['grafico','descendo','queda'] },
      { emoji: '🎨', keywords: ['paleta','arte','cores','pintura'] },
      { emoji: '🎵', keywords: ['nota','musica','melodia'] },
      { emoji: '🎶', keywords: ['notas','musica','melodia'] },
      { emoji: '📚', keywords: ['livros','estudo','biblioteca'] },
      { emoji: '📖', keywords: ['livro','aberto','leitura'] },
      { emoji: '📕', keywords: ['livro','vermelho','fechado'] },
      { emoji: '🏠', keywords: ['casa','lar','home','moradia'] },
      { emoji: '💼', keywords: ['maleta','trabalho','negocios'] },
      { emoji: '🗂️', keywords: ['pasta','divisor','arquivo'] },
      { emoji: '📂', keywords: ['pasta','aberta','arquivo'] },
      { emoji: '📁', keywords: ['pasta','fechada','arquivo'] },
      { emoji: '🗒️', keywords: ['bloco','notas','caderno'] },
      { emoji: '✏️', keywords: ['lapis','escrever','editar'] },
      { emoji: '🖊️', keywords: ['caneta','escrever'] },
      { emoji: '🖍️', keywords: ['giz','cera','colorir'] },
      { emoji: '📐', keywords: ['esquadro','regua','angulo'] },
      { emoji: '📏', keywords: ['regua','medir'] },
      { emoji: '🔒', keywords: ['cadeado','trancado','seguro'] },
      { emoji: '🔓', keywords: ['cadeado','aberto','destrancado'] },
      { emoji: '🔑', keywords: ['chave','acesso','senha'] },
      { emoji: '🗝️', keywords: ['chave','antiga','tesouro'] },
      { emoji: '🔍', keywords: ['lupa','buscar','pesquisar'] },
      { emoji: '🔎', keywords: ['lupa','direita','buscar'] },
      { emoji: '💎', keywords: ['diamante','joia','valioso'] },
      { emoji: '🧲', keywords: ['ima','magnetico','atrair'] },
      { emoji: '🔧', keywords: ['chave','inglesa','ferramenta'] },
      { emoji: '🔨', keywords: ['martelo','ferramenta','construir'] },
      { emoji: '⚙️', keywords: ['engrenagem','configuracao','config'] },
      { emoji: '🛠️', keywords: ['ferramentas','martelo','chave'] },
      { emoji: '📦', keywords: ['caixa','pacote','entrega'] },
      { emoji: '🏷️', keywords: ['etiqueta','tag','preco'] },
      { emoji: '🧾', keywords: ['recibo','nota','fiscal'] },
      { emoji: '🎁', keywords: ['presente','caixa','surpresa'] },
      { emoji: '📱', keywords: ['celular','telefone','smartphone'] },
      { emoji: '💻', keywords: ['computador','laptop','notebook'] },
      { emoji: '🖥️', keywords: ['computador','desktop','tela'] },
      { emoji: '⌨️', keywords: ['teclado','digitar'] },
      { emoji: '🖨️', keywords: ['impressora','imprimir'] },
      { emoji: '📷', keywords: ['camera','foto','fotografia'] },
      { emoji: '📹', keywords: ['camera','video','filmadora'] },
      { emoji: '🎥', keywords: ['cinema','filme','camera'] },
      { emoji: '📺', keywords: ['televisao','tv','assistir'] },
      { emoji: '🎙️', keywords: ['microfone','podcast','gravar'] },
      { emoji: '🎧', keywords: ['fone','ouvido','musica'] },
      { emoji: '🎸', keywords: ['guitarra','musica','rock'] },
      { emoji: '🎹', keywords: ['piano','teclado','musica'] },
      { emoji: '🎺', keywords: ['trompete','musica','sopro'] },
      { emoji: '🥁', keywords: ['bateria','tambor','musica'] },
      { emoji: '⏰', keywords: ['relogio','alarme','despertar'] },
      { emoji: '⏳', keywords: ['ampulheta','tempo','espera'] },
      { emoji: '🔔', keywords: ['sino','notificacao','alerta'] },
      { emoji: '🔕', keywords: ['sino','mudo','silencioso'] },
      { emoji: '📧', keywords: ['email','correio','mensagem'] },
      { emoji: '✉️', keywords: ['carta','envelope','correio'] },
      { emoji: '📮', keywords: ['caixa','correio','carta'] },
      { emoji: '🗑️', keywords: ['lixeira','lixo','deletar'] },
    ],
  },
  {
    id: 'activities',
    label: 'Atividades e Esporte',
    icon: '⚽',
    emojis: [
      { emoji: '⚽', keywords: ['futebol','bola','esporte'] },
      { emoji: '🏀', keywords: ['basquete','bola','esporte'] },
      { emoji: '🏈', keywords: ['futebol','americano','bola'] },
      { emoji: '⚾', keywords: ['baseball','bola','esporte'] },
      { emoji: '🎾', keywords: ['tenis','bola','esporte'] },
      { emoji: '🏐', keywords: ['volei','bola','esporte'] },
      { emoji: '🎱', keywords: ['sinuca','bilhar','bola'] },
      { emoji: '🏓', keywords: ['ping','pong','tenis','mesa'] },
      { emoji: '🏸', keywords: ['badminton','raquete'] },
      { emoji: '🏒', keywords: ['hockey','gelo','esporte'] },
      { emoji: '🥊', keywords: ['boxe','luva','luta'] },
      { emoji: '🎿', keywords: ['esqui','neve','inverno'] },
      { emoji: '🏄', keywords: ['surf','onda','praia'] },
      { emoji: '🏊', keywords: ['natacao','nadar','piscina'] },
      { emoji: '🚴', keywords: ['ciclismo','bicicleta','pedal'] },
      { emoji: '🏋️', keywords: ['musculacao','peso','academia'] },
      { emoji: '🧘', keywords: ['yoga','meditacao','zen'] },
      { emoji: '🎮', keywords: ['controle','jogo','videogame'] },
      { emoji: '🎲', keywords: ['dado','jogo','sorte'] },
      { emoji: '🎭', keywords: ['teatro','mascara','drama'] },
      { emoji: '🎬', keywords: ['cinema','filme','acao'] },
      { emoji: '🎤', keywords: ['microfone','cantar','karaoke'] },
      { emoji: '🎳', keywords: ['boliche','bola','pinos'] },
      { emoji: '🏆', keywords: ['trofeu','campeao','vencedor'] },
      { emoji: '🥇', keywords: ['medalha','ouro','primeiro'] },
      { emoji: '🥈', keywords: ['medalha','prata','segundo'] },
      { emoji: '🥉', keywords: ['medalha','bronze','terceiro'] },
      { emoji: '🏅', keywords: ['medalha','esporte','premio'] },
      { emoji: '🎖️', keywords: ['medalha','militar','honra'] },
      { emoji: '🎪', keywords: ['circo','tenda','show'] },
    ],
  },
  {
    id: 'travel',
    label: 'Viagem e Lugares',
    icon: '✈️',
    emojis: [
      { emoji: '🚗', keywords: ['carro','automovel','veiculo'] },
      { emoji: '🚕', keywords: ['taxi','carro','amarelo'] },
      { emoji: '🚌', keywords: ['onibus','transporte','publico'] },
      { emoji: '🚎', keywords: ['trem','onibus','eletrico'] },
      { emoji: '🏎️', keywords: ['carro','corrida','formula'] },
      { emoji: '🚓', keywords: ['policia','carro','viatura'] },
      { emoji: '🚑', keywords: ['ambulancia','emergencia','hospital'] },
      { emoji: '🚒', keywords: ['bombeiro','caminhao','incendio'] },
      { emoji: '🚐', keywords: ['van','onibus','transporte'] },
      { emoji: '🛻', keywords: ['picape','caminhonete','truck'] },
      { emoji: '🚚', keywords: ['caminhao','entrega','mudanca'] },
      { emoji: '✈️', keywords: ['aviao','voo','viagem'] },
      { emoji: '🚀', keywords: ['foguete','espaco','lancamento'] },
      { emoji: '🛸', keywords: ['ovni','ufo','disco','voador'] },
      { emoji: '🚁', keywords: ['helicoptero','voo'] },
      { emoji: '🛶', keywords: ['canoa','barco','remo'] },
      { emoji: '⛵', keywords: ['veleiro','barco','mar'] },
      { emoji: '🚢', keywords: ['navio','cruzeiro','barco'] },
      { emoji: '🏰', keywords: ['castelo','medieval','torre'] },
      { emoji: '🗼', keywords: ['torre','eiffel','paris'] },
      { emoji: '🗽', keywords: ['liberdade','estatua','nova','york'] },
      { emoji: '⛩️', keywords: ['torii','japao','santuario'] },
      { emoji: '🕌', keywords: ['mesquita','oracao','religiao'] },
      { emoji: '⛪', keywords: ['igreja','religiao','cruz'] },
      { emoji: '🏥', keywords: ['hospital','saude','medico'] },
      { emoji: '🏦', keywords: ['banco','dinheiro','financas'] },
      { emoji: '🏫', keywords: ['escola','estudo','educacao'] },
      { emoji: '🏢', keywords: ['predio','escritorio','empresa'] },
      { emoji: '🏭', keywords: ['fabrica','industria'] },
      { emoji: '🏖️', keywords: ['praia','ferias','sol'] },
      { emoji: '🏕️', keywords: ['acampamento','barraca','camping'] },
      { emoji: '🗺️', keywords: ['mapa','mundo','viagem'] },
      { emoji: '🧭', keywords: ['bussola','direcao','norte'] },
    ],
  },
  {
    id: 'symbols',
    label: 'Bandeiras e Símbolos',
    icon: '🔴',
    emojis: [
      { emoji: '🏁', keywords: ['bandeira','quadriculada','chegada'] },
      { emoji: '🚩', keywords: ['bandeira','vermelha','alerta'] },
      { emoji: '🎌', keywords: ['bandeiras','cruzadas'] },
      { emoji: '🏴', keywords: ['bandeira','preta'] },
      { emoji: '🏳️', keywords: ['bandeira','branca','rendição'] },
      { emoji: '🇧🇷', keywords: ['brasil','bandeira','br'] },
      { emoji: '🇺🇸', keywords: ['eua','estados','unidos','usa'] },
      { emoji: '🇵🇹', keywords: ['portugal','bandeira','pt'] },
      { emoji: '🇪🇸', keywords: ['espanha','bandeira'] },
      { emoji: '🇫🇷', keywords: ['franca','bandeira'] },
      { emoji: '🇩🇪', keywords: ['alemanha','bandeira'] },
      { emoji: '🇯🇵', keywords: ['japao','bandeira'] },
      { emoji: '🇬🇧', keywords: ['reino','unido','inglaterra'] },
      { emoji: '🔴', keywords: ['circulo','vermelho'] },
      { emoji: '🟠', keywords: ['circulo','laranja'] },
      { emoji: '🟡', keywords: ['circulo','amarelo'] },
      { emoji: '🟢', keywords: ['circulo','verde'] },
      { emoji: '🔵', keywords: ['circulo','azul'] },
      { emoji: '🟣', keywords: ['circulo','roxo'] },
      { emoji: '⚫', keywords: ['circulo','preto'] },
      { emoji: '⚪', keywords: ['circulo','branco'] },
      { emoji: '🟤', keywords: ['circulo','marrom'] },
      { emoji: '🔶', keywords: ['losango','laranja','grande'] },
      { emoji: '🔷', keywords: ['losango','azul','grande'] },
      { emoji: '🔸', keywords: ['losango','laranja','pequeno'] },
      { emoji: '🔹', keywords: ['losango','azul','pequeno'] },
      { emoji: '▪️', keywords: ['quadrado','preto','pequeno'] },
      { emoji: '▫️', keywords: ['quadrado','branco','pequeno'] },
      { emoji: '◾', keywords: ['quadrado','preto','medio'] },
      { emoji: '◽', keywords: ['quadrado','branco','medio'] },
      { emoji: '⬛', keywords: ['quadrado','preto','grande'] },
      { emoji: '⬜', keywords: ['quadrado','branco','grande'] },
      { emoji: '💠', keywords: ['diamante','ponto'] },
      { emoji: '🔘', keywords: ['radio','botao'] },
      { emoji: '🔲', keywords: ['botao','quadrado','preto'] },
      { emoji: '🔳', keywords: ['botao','quadrado','branco'] },
      { emoji: '✔️', keywords: ['check','correto','certo'] },
      { emoji: '✖️', keywords: ['x','errado','multiplicar'] },
      { emoji: '➕', keywords: ['mais','adicionar','somar'] },
      { emoji: '➖', keywords: ['menos','subtrair','tirar'] },
      { emoji: '➗', keywords: ['dividir','divisao'] },
      { emoji: '❓', keywords: ['interrogacao','pergunta','duvida'] },
      { emoji: '❗', keywords: ['exclamacao','alerta','importante'] },
      { emoji: '‼️', keywords: ['exclamacao','dupla','urgente'] },
      { emoji: '⚠️', keywords: ['aviso','alerta','atencao'] },
      { emoji: '♻️', keywords: ['reciclar','reciclagem','ambiente'] },
      { emoji: '🔱', keywords: ['tridente','poseidon'] },
      { emoji: '⚜️', keywords: ['flor','lis','emblema'] },
      { emoji: '🔰', keywords: ['iniciante','japones'] },
      { emoji: '♾️', keywords: ['infinito','eterno'] },
      { emoji: '🆕', keywords: ['novo','new'] },
      { emoji: '🆗', keywords: ['ok','certo'] },
      { emoji: '🆙', keywords: ['up','cima','legal'] },
      { emoji: '🆒', keywords: ['cool','legal'] },
      { emoji: '🆓', keywords: ['free','gratis'] },
      { emoji: '🆘', keywords: ['sos','socorro','ajuda'] },
      { emoji: '🔄', keywords: ['atualizar','recarregar','loop'] },
      { emoji: '⏪', keywords: ['voltar','retroceder','rapido'] },
      { emoji: '⏩', keywords: ['avancar','rapido'] },
      { emoji: '⏫', keywords: ['subir','cima','rapido'] },
      { emoji: '⏬', keywords: ['descer','baixo','rapido'] },
    ],
  },
  {
    id: 'celebrations',
    label: 'Celebração',
    icon: '🎉',
    emojis: [
      { emoji: '🎉', keywords: ['festa','confete','celebracao'] },
      { emoji: '🎊', keywords: ['confete','bola','festa'] },
      { emoji: '🎈', keywords: ['balao','festa','aniversario'] },
      { emoji: '🎀', keywords: ['laco','presente','rosa'] },
      { emoji: '🎁', keywords: ['presente','caixa','surpresa'] },
      { emoji: '🎂', keywords: ['bolo','aniversario','vela'] },
      { emoji: '🎄', keywords: ['arvore','natal','dezembro'] },
      { emoji: '🎅', keywords: ['papai','noel','natal'] },
      { emoji: '🤶', keywords: ['mamae','noel','natal'] },
      { emoji: '🎆', keywords: ['fogos','artificio','ano','novo'] },
      { emoji: '🎇', keywords: ['sparkler','fogos','brilho'] },
      { emoji: '🧨', keywords: ['bombinha','explosao','festa'] },
      { emoji: '✨', keywords: ['brilho','estrela','magico'] },
      { emoji: '⭐', keywords: ['estrela','favorito','destaque'] },
      { emoji: '🌟', keywords: ['estrela','brilhante','destaque'] },
      { emoji: '⚡', keywords: ['raio','eletrico','energia'] },
      { emoji: '🔥', keywords: ['fogo','quente','popular'] },
      { emoji: '🎗️', keywords: ['fita','conscientizacao','laco'] },
      { emoji: '🎟️', keywords: ['ingresso','bilhete','evento'] },
      { emoji: '🎫', keywords: ['ingresso','ticket','evento'] },
      { emoji: '👑', keywords: ['coroa','rei','rainha','real'] },
      { emoji: '💍', keywords: ['anel','casamento','diamante'] },
      { emoji: '🏆', keywords: ['trofeu','campeao','vencedor'] },
    ],
  },
];

// Flatten all emojis for search
export function searchEmojis(query: string): EmojiEntry[] {
  if (!query.trim()) return [];
  const q = query.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '');
  const results: EmojiEntry[] = [];
  const seen = new Set<string>();
  for (const cat of EMOJI_CATEGORIES) {
    for (const entry of cat.emojis) {
      if (seen.has(entry.emoji)) continue;
      const match = entry.keywords.some(k => {
        const nk = k.normalize('NFD').replace(/[\u0300-\u036f]/g, '');
        return nk.includes(q);
      }) || entry.emoji.includes(query);
      if (match) {
        results.push(entry);
        seen.add(entry.emoji);
      }
    }
  }
  return results;
}
