import {
  Folder,
  FolderOpen,
  Briefcase,
  Home,
  Star,
  Heart,
  Zap,
  Target,
  Flag,
  Bookmark,
  Tag,
  Gift,
  Trophy,
  Crown,
  Rocket,
  Lightbulb,
  Compass,
  Map,
  Globe,
  Building,
  User,
  Users,
  Code,
  Terminal,
  Laptop,
  Smartphone,
  Camera,
  Music,
  Book,
  GraduationCap,
  Dumbbell,
  Utensils,
  Plane,
  Car,
  Bike,
  Ship,
  Mountain,
  Sun,
  Moon,
  Cloud,
  Umbrella,
  Flame,
  Droplet,
  Leaf,
  Flower,
  TreeDeciduous,
  Apple,
  Coffee,
  Pizza,
  Cake,
  Wine,
  Beer,
  ShoppingBag,
  CreditCard,
  Wallet,
  PiggyBank,
  BarChart3,
  LineChart,
  Calendar,
  Clock,
  AlarmClock,
  Timer,
  Hourglass,
  Bell,
  Mail,
  MessageCircle,
  Phone,
  Video,
  Mic,
  Headphones,
  Speaker,
  Radio,
  Tv,
  Gamepad2,
  Puzzle,
  Dice5,
  Palette,
  Brush,
  Pen,
  Pencil,
  Scissors,
  Ruler,
  Wrench,
  Hammer,
  Key,
  Lock,
  Shield,
  Award,
  Medal,
  Gem,
  Diamond,
  Coins,
  Banknote,
  Receipt,
  Shirt,
  type LucideIcon,
} from 'lucide-react';
import { cn } from '@/lib/utils';

const iconMap: Record<string, LucideIcon> = {
  'folder': Folder,
  'folder-open': FolderOpen,
  'briefcase': Briefcase,
  'home': Home,
  'star': Star,
  'heart': Heart,
  'zap': Zap,
  'target': Target,
  'flag': Flag,
  'bookmark': Bookmark,
  'tag': Tag,
  'gift': Gift,
  'trophy': Trophy,
  'crown': Crown,
  'rocket': Rocket,
  'lightbulb': Lightbulb,
  'compass': Compass,
  'map': Map,
  'globe': Globe,
  'building': Building,
  'user': User,
  'users': Users,
  'code': Code,
  'terminal': Terminal,
  'laptop': Laptop,
  'smartphone': Smartphone,
  'camera': Camera,
  'music': Music,
  'book': Book,
  'graduation-cap': GraduationCap,
  'dumbbell': Dumbbell,
  'utensils': Utensils,
  'plane': Plane,
  'car': Car,
  'bike': Bike,
  'ship': Ship,
  'mountain': Mountain,
  'sun': Sun,
  'moon': Moon,
  'cloud': Cloud,
  'umbrella': Umbrella,
  'flame': Flame,
  'droplet': Droplet,
  'leaf': Leaf,
  'flower': Flower,
  'tree': TreeDeciduous,
  'apple': Apple,
  'coffee': Coffee,
  'pizza': Pizza,
  'cake': Cake,
  'wine': Wine,
  'beer': Beer,
  'shopping-bag': ShoppingBag,
  'credit-card': CreditCard,
  'wallet': Wallet,
  'piggy-bank': PiggyBank,
  'chart-bar': BarChart3,
  'chart-line': LineChart,
  'calendar': Calendar,
  'clock': Clock,
  'alarm-clock': AlarmClock,
  'timer': Timer,
  'hourglass': Hourglass,
  'bell': Bell,
  'mail': Mail,
  'message-circle': MessageCircle,
  'phone': Phone,
  'video': Video,
  'mic': Mic,
  'headphones': Headphones,
  'speaker': Speaker,
  'radio': Radio,
  'tv': Tv,
  'gamepad': Gamepad2,
  'puzzle': Puzzle,
  'dice': Dice5,
  'palette': Palette,
  'brush': Brush,
  'pen': Pen,
  'pencil': Pencil,
  'scissors': Scissors,
  'ruler': Ruler,
  'wrench': Wrench,
  'hammer': Hammer,
  'key': Key,
  'lock': Lock,
  'shield': Shield,
  'award': Award,
  'medal': Medal,
  'gem': Gem,
  'diamond': Diamond,
  'coins': Coins,
  'banknote': Banknote,
  'receipt': Receipt,
  'shirt': Shirt,
};

interface FolderIconRendererProps {
  icon: string;
  color?: string;
  className?: string;
}

export function FolderIconRenderer({ icon, color, className }: FolderIconRendererProps) {
  const IconComponent = iconMap[icon] || Folder;
  
  return (
    <IconComponent 
      className={cn(className)}
      style={color ? { color } : undefined}
    />
  );
}
